version: '3'
services:
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./site:/app:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php

  php:
    build:
      ./docker/php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./site:/app:delegated
      - ./docker/php/php-fpm.ini:/etc/php/php.ini
    links:
      - pgsql:postgresql

  pgsql:
      image: postgres:9
      volumes:
        - ./docker/pgsql/db:/var/lib/postgresql
        - ./docker/pgsql/db_user_init.sql:/tmp/db_user_init.sql
      environment:
        POSTGRES_PASSWORD: qwerty